### ISSUE TITLE
Edgecolor

### ISSUE THREAD

**Issue by mkkubins** [wiheto/netplotbrain#45]
Hi, 

I would like to ask if this is possible to modify the edge_color input to get the list or NumPy array that represents each edge color? 
I think these is only two lines of modifications where: 
` if isinstance(edgecolor, np.ndarray):
            if edgecolor.shape[0] == len(edges):
                ec = edgecolor[eci, :]`

can be changed to:
`    if isinstance(edgecolor, np.ndarray) or isinstance(edgecolor, list):
            if len(edgecolor) == len(edges):
                ec = edgecolor[eci]`

When I am using the current code and I want to pass the NumPy array with the colors for each edge then I have an error:
`ValueError: array(['#6c1fff', '#68fcc1', '#1dd1e2', '#149df1', '#08bee9', '#2adddd',
       '#4a53fb', '#08bee9', '#4a53fb', '#622ffe', '#149df1', '#622ffe',
       '#6c1fff', '#68fcc1', '#1dd1e2', '#2adddd'], dtype='<U7') is not a valid value for color` 

I would like to have the color for each edge based on the connectivity values. 

Best, 
Marta

**Comment by wiheto** [comment]
Hi, 

Thanks for finding something you think could be improved. 

This should be a possible workaround for now (basically transforming your edgecolor numpy array to a pandas dataframe and adding it as additional input): 

```
import numpy as np
import pandas as pd
# get upper all upper triangular indicies
# Assumes edgecolor is a NxN np.array
i_ind, j_ind = np.triu_indicies(edgecolor.shape[0], k=1)
# Make a 3 column dataframe with i, j and the edge color 
edges_df = pd.Dataframe(data={'i': i_ind, 'j': j_ind, 'edgecolor': edgecolor[i_ind, j_ind]})

netplotbrain.plot(edges=edges, edges_df=edges_df, edgecolor='edgecolor')
```

Let me know if this works (and makes sense). 

As for adding your fix to your problem, feel free to submit your proposed changes as a pull request as well and I will review them asap. Or if you want me to fix it, I will get to it in a few weeks when I am back at work (currently on holiday so doing less programming at the moment). Hope that is OK!

**Comment by wiheto** [comment]
Also, one more question, if you currently pass (without my workaround):

`netplotbrain.plot(..., edgecolor=np.array(edgecolor))`

where "..." is the rest of your input, do you still get the same error?

**Comment by mkkubins** [comment]
Yes, I think the problem is that I am passing the array with shape `(len(edges),)` and when I reshape this to `(len(edges),1)` then it becomes something like: `np.array(['blue'],['red'])`.  So in the code `edgecolor[eci, :]`  it required the 2D array, where my data are 1D. 

This is my input array: 
`array(['#6c1fff', '#68fcc1', '#1dd1e2', '#149df1', '#08bee9', '#2adddd', '#4a53fb', '#08bee9', '#4a53fb', '#622ffe', '#149df1', '#622ffe', '#6c1fff', '#68fcc1', '#1dd1e2', '#2adddd'], dtype='<U7') `

And after reshape to  `(len(edges),1)`:
`array([['#6c1fff'],
       ['#68fcc1'],
       ['#1dd1e2'],
       ['#149df1'],
       ['#08bee9'],
       ['#2adddd'],
       ['#4a53fb'],
       ['#08bee9'],
       ['#4a53fb'],
       ['#622ffe'],
       ['#149df1'],
       ['#622ffe'],
       ['#6c1fff'],
       ['#68fcc1'],
       ['#1dd1e2'],
       ['#2adddd']], dtype='<U7') `

But your solution works also and I think it's nice! Thanks for the help and have a nice holiday

**Comment by wiheto** [comment]
In 0.2.2 (current 0.2.2a4) this should now work by:

1. specifying custom colors as edge_cmap as a list of colors. 
2. specifying the colors directly in the data frame for each edge. 

Sorry it took so long to get to it. I thought the workaround was working (somehow missed that it wasn't). 

Reopen this issue if you still get problems.

**Comment by wiheto** [comment]
See for example https://www.netplotbrain.org/gallery/specifying_node_color/ and https://www.netplotbrain.org/gallery/node_cmap/ (2nd link should be active within 10 minutes after posting this comment) for how to do this for nodes. Same logic work for edge_color and edge_cmap
