### ISSUE TITLE
ENH: Check templateflow compatibility

### ISSUE THREAD

**Issue by wiheto** [wiheto/netplotbrain#6]
Check template compatibility with all atlases. If not, make json for special settings for each

- [x] glass
- [ ]  cloudy
- [ ]  surface
- [ ]  filled

Note: heavily edited comment

**Comment by oesteban** [comment]
What does checking one of the templates above requires?

**Comment by wiheto** [comment]
I was just going through each one to make sure a single image was selected for each template, making sure a variable is selected and that none of the brain is cut off.

Most will work straight away, I just havn't had time to check all of them yet.

**Comment by wiheto** [comment]
And the main reason was I got stuck on the multiple cohorts for the infant templates (e.g. MNIInfant). Do you know if there is one default template that is always used, or is the cohort always specified?
