### ISSUE TITLE
node coordinates(x,y,z) definition

### ISSUE THREAD

**Issue by YuanYuan527** [wiheto/netplotbrain#64]
I would like to ask whether the coordinates XYZ in the node represent the index of the image, similar to IJK, or represent the world coordinate system, such as the RAS coordinate system or the LPS coordinate system. The situation is not explained in the document

**Comment by wiheto** [comment]
Yes. 

But it can be any coordinate system which is based on the template image used.

X is the first dimension, Y the second, and Z the third of whatever template image is used. 

Is that clear?
